"""create portfolios table

Revision ID: f8b198c633f3
Revises: 3fe339ccd06c
Create Date: 2026-09-12 00:29:58.625612

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f8b198c633f3'
down_revision: str | Sequence[str] | None = '3fe339ccd06c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('portfolio', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(), nullable=True),
    sa.Column('risk_category_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['alor.accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'portfolio', 'exchange'),
    schema='alor'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios', schema='alor')
    # ### end Alembic commands ###
